create table if not exists users (
    id    bigint generated by default as identity primary key,
    email varchar(254) not null unique,
    name  varchar(250) not null
);

create table if not exists categories (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table if not exists events (
    id                   bigint generated by default as identity primary key,
    title                varchar(120) not null,
    annotation           text not null,
    description          text not null,
    event_date           timestamp not null,
    created_on           timestamp not null,
    published_on         timestamp,
    paid                 boolean not null default false,
    participant_limit    integer not null default 0,
    request_moderation   boolean not null default true,
    confirmed_requests   bigint not null default 0,
    state                varchar(20) not null,
    lat                  double precision not null,
    lon                  double precision not null,
    initiator_id         bigint not null,
    category_id          bigint not null,

    constraint fk_event_user
        foreign key (initiator_id) references users(id),

    constraint fk_event_category
        foreign key (category_id) references categories(id)
);

create table if not exists requests (
    id            bigint generated by default as identity primary key,
    created       timestamp not null,
    status        varchar(20) not null,
    requester_id  bigint not null,
    event_id      bigint not null,

    constraint uq_request unique (requester_id, event_id),

    constraint fk_request_user
        foreign key (requester_id) references users(id),

    constraint fk_request_event
        foreign key (event_id) references events(id)
);

create table if not exists compilations (
    id     bigint generated by default as identity primary key,
    title  varchar(50) not null,
    pinned boolean not null default false
);

create table if not exists compilation_events (
    compilation_id bigint not null,
    event_id       bigint not null,

    constraint pk_compilation_events primary key (compilation_id, event_id),

    constraint fk_compilation
        foreign key (compilation_id) references compilations(id),

    constraint fk_compilation_event
        foreign key (event_id) references events(id)
);
